heat_template_version: 2015-04-30

description: Network fragment

parameters:
  stack_name:
    type: string
  key_value:
    type: string
  public_net:
    type: string
    description: ID or name of public network for which router will be allocated.
  nameservers:
    type: comma_delimited_list
  network_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 172.16.10.0/24
  network_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 172.16.10.90
  network_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 172.16.10.200

resources:
  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: stack_name }
      public_key: { get_param: key_value }
      save_private_key: false
  network:
    type: OS::Neutron::Net
    properties:
      name: { list_join: ['-', [get_param: stack_name, 'private']] }
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ['-', [get_param: stack_name, 'private']] }
      network: { get_resource: network }
      cidr: { get_param: network_cidr }
      dns_nameservers: { get_param: nameservers }
      allocation_pools:
        - start: { get_param: network_pool_start }
          end: { get_param: network_pool_end }
  router:
    type: OS::Neutron::Router
    properties:
      name: { list_join: ['-', [get_param: stack_name, 'router']] }
      external_gateway_info:
        network: { get_param: public_net }
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: private_subnet }
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: stack_name }
      description: Security group
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
outputs:
  network:
    value: { get_attr: [network, name] }
  security_group:
    value: { get_param: stack_name }

