heat_template_version: 2015-10-15

description: 3 single nodes fragment

parameters:
  key_pair:
    type: string
  network:
    type: string
  security_group:
    type: string
  instance01_name:
    type: string
  instance02_name:
    type: string
  instance03_name:
    type: string
  instance_domain:
    type: string
  instance_cluster:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_config_host:
    type: string
  instance_cloud_init:
    type: string
    default: ""

resources:
  instance01:
    type: MCP::SingleInstance
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      security_group: { get_param: security_group }
      instance_name: { get_param: instance01_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
  instance02:
    type: MCP::SingleInstance
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      security_group: { get_param: security_group }
      instance_name: { get_param: instance02_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
  instance03:
    type: MCP::SingleInstance
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      security_group: { get_param: security_group }
      instance_name: { get_param: instance03_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
